### ISSUE TITLE
Security vulnerabilities and classpath issues in the jar

### ISSUE THREAD

**Issue by emaayan** [aws/aws-greengrass-core-sdk-java#7]
the jar is bundled with classes from 3rd party libraries, (slf4j, beans validation and jackson-databind)

including those inside the jar can cause major classpath problems if coupled with transitive dependencies of different versions.

additionally the jackson library used is version 2.9.9 which contains several reported Security vulnerabilities.

the jar should at least contain only the relavent classes to it's operation.

**Comment by thingstiger** [comment]
As soon as you add another AWS SDK dependency, for example, StreamManager will fail with errors like 'stream closed', mapdb corruption, serialization errors, etc.
This is due to jackson classpath conflicts as @emaayan mentioned. no surprise at all.

Removing all the bundled dependencies and managing them with gradle or maven instead fixed all these problems.

The jar as provided is totally useless, except for quickly creating a hello world app that integrates with no other services. The jar should not contain bundled classes and ideally, be available on maven central - manually adding binary jars to projects isn't a very manageable approach.

I'm not sure why this library is in this state. Is this already superseded by a new version, or no one uses it?

**Comment by sushantAtAws** [comment]
We have updated the repo with a `slim` jar file which does not build in the dependencies. The README has been updated with the list of dependencies required.
